name: Keep Alive

on:
  schedule:
    - cron: '0 12 1 * *'  # prvi dan u mesecu u podne

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dummy commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit --allow-empty -m "keepalive"
          git push
